// Generated by CoffeeScript 1.7.1
(function() {
  var assert, equ, processors;

  processors = require('../lib/processors');

  assert = require('assert');

  equ = assert.equal;

  module.exports = {
    'test normalize': function(test) {
      var demo, result;
      demo = 'This shOUld BE loWErcase';
      result = processors.normalize(demo);
      equ(result, 'this should be lowercase');
      return test.done();
    },
    'test firstCharLowerCase': function(test) {
      var demo, result;
      demo = 'ThiS SHould OnlY LOwercase the fIRST cHar';
      result = processors.firstCharLowerCase(demo);
      equ(result, 'thiS SHould OnlY LOwercase the fIRST cHar');
      return test.done();
    },
    'test stripPrefix': function(test) {
      var demo, result;
      demo = 'stripMe:DoNotTouch';
      result = processors.stripPrefix(demo);
      equ(result, 'DoNotTouch');
      return test.done();
    },
    'test stripPrefix, ignore xmlns': function(test) {
      var demo, result;
      demo = 'xmlns:shouldHavePrefix';
      result = processors.stripPrefix(demo);
      equ(result, 'xmlns:shouldHavePrefix');
      return test.done();
    }
  };

}).call(this);
