// Generated by CoffeeScript 1.7.1
(function() {
  var events, js2xmlparser,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  js2xmlparser = require('js2xmlparser');

  events = require('events');

  exports.defaults = {
    xmlEncoding: null,
    attributeString: "@",
    colorPalette: ['0', '0000FF', 'FF0000', 'FFFFFF'],
    static_image_sizes: {
      'chkmrk_x': {
        width: 29,
        height: 30
      },
      'chkmrk_v': {
        width: 29,
        height: 29
      },
      'chkmrk_o': {
        width: 26,
        height: 30
      }
    }
  };

  exports.Parser = (function(_super) {
    __extends(Parser, _super);

    function Parser() {
      this.parseJson = __bind(this.parseJson, this);
      return Parser.__super__.constructor.apply(this, arguments);
    }

    Parser.prototype.convertAll = function(data) {
      var newPages, obj, page, pageId, _i, _len, _ref, _ref1, _ref2, _ref3;
      this.convert(data);
      _ref = data.content.page;
      for (pageId in _ref) {
        page = _ref[pageId];
        this.convert(page);
      }
      _ref1 = data.content.page;
      for (pageId in _ref1) {
        page = _ref1[pageId];
        if (page.obj) {
          _ref2 = page.obj;
          for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
            obj = _ref2[_i];
            this.convert(obj);
          }
        }
      }
      newPages = [];
      _ref3 = data.content.page;
      for (pageId in _ref3) {
        page = _ref3[pageId];
        newPages.push(page);
      }
      return data.content.page = newPages;
    };

    Parser.prototype.DenormalizedPosition = function(obj, size) {
      var scale;
      scale = obj.size || 1;
      obj.x += Math.round(size.width * scale);
      return obj.y += Math.round(size.height * scale);
    };

    Parser.prototype.convert = function(data) {
      var crv, _i, _len, _ref;
      data['@'] = {};
      if (data.localID != null) {
        delete data.localID;
      }
      if (data.crv != null) {
        data.xml_list.crv = data.crv;
        delete data.crv;
      }
      if (data.thickness != null) {
        data.t = data.thickness;
        delete data.thickness;
      }
      if (data.smoothing != null) {
        data.s = data.smoothing;
        delete data.smoothing;
      }
      if (data.color != null) {
        data.c = data.color;
        delete data.color;
      }
      if (data.controlPoints != null) {
        data['_'] = data.controlPoints;
        delete data.controlPoints;
      }
      if (data.id != null) {
        data['@'].id = data.id;
        delete data.id;
      }
      if (data.ver != null) {
        data['@'].ver = data.ver;
        delete data.ver;
      }
      if (data.encoded != null) {
        data['@'].encoded = data.encoded;
        delete data.encoded;
      }
      if (data.t != null) {
        data['@'].t = data.t;
        delete data.t;
      }
      if (data.s != null) {
        data['@'].s = data.s;
        delete data.s;
      }
      if (data.c != null) {
        data['@'].c = data.c;
        delete data.c;
      }
      if (data.xml_list != null) {
        _ref = data.xml_list.crv;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          crv = _ref[_i];
          this.convert(crv);
        }
      }
      if ((data.type != null) && data.type in exports.defaults.static_image_sizes) {
        this.DenormalizedPosition(data, exports.defaults.static_image_sizes[data.type]);
      }
      if ((data.data != null) && (data.data.controlPoints != null)) {
        data.data.controlPoints = data.data.controlPoints.join(',');
      }
      if (data.imageId != null) {
        data.image_id = 's' + data.imageId;
        delete data.imageId;
      }
      return data;
    };

    Parser.prototype.parseJson = function(json, cb) {
      var result;
      this.convertAll(json);
      result = js2xmlparser('content', json.content, exports.defaults);
      result = result.replace(/<_[^>]*>/g, '');
      result = result.replace(/<\/_[^>]*>/g, '');
      return cb(null, result);
    };

    return Parser;

  })(events.EventEmitter);

  exports.parseJson = function(json, a, b) {
    var cb, options, parser;
    if (b != null) {
      if (typeof b === 'function') {
        cb = b;
      }
      if (typeof a === 'object') {
        options = a;
      }
    } else {
      if (typeof a === 'function') {
        cb = a;
      }
      options = {};
    }
    parser = new exports.Parser(options);
    return parser.parseJson(json, cb);
  };

}).call(this);
